backend:
  name: git-gateway

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://abo-showroom.netlify.app"

collections:
  - name: spot
    label: Spots
    folder: src/content/spots
    create: true
    format: frontmatter
    preview_path: spot/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { label: "Publish", name: "isPublish", widget: "boolean", default: true }
      - { label: "Draft", name: "isDraft", widget: "boolean", default: false }
      - { name: body, label: Body, widget: markdown }
      - { label: Position, name: position, widget: string }
      - { label: Photo, name: photo, widget: image }
  - name: post
    label: Posts
    folder: src/content/posts
    create: true
    format: frontmatter
    preview_path: post/{{slug}}
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: publishedAt, label: Date, widget: date }
      - { label: "Publish", name: "isPublish", widget: "boolean", default: true }
      - { label: "Draft", name: "isDraft", widget: "boolean", default: false }
      - { name: body, label: Body, widget: markdown }
